reflection: 'off'

image_extension: '.png'
data_stride: 15
data_seq_len: 1
data_resize: [201, 201]

full_size_image_folder: 'frames_rotated'
cropped_image_folder: 'databases'
super_resolution_cropped : 'databases_SR'

SROF: 'result.csv' #'result_2Pass_corrected.csv'

Dataset:
  Dataset_Root          : '/media/d25u2/Dont/Viscosity' # base path to the dataset
  wide                  : False # using the full landscape images or only cropped droplets
  super_resolution      : False  # whether to use super-resolution cropped images
  resize: {
            True                  : [1280, 512], # for full landscape images
            False                 : [201 , 201]  # for cropped case
          }
  reflection_removal    : False # whether to remove reflection artifacts in images

  embedding:
    positional_encoding   : 'Velocity' # choosing what kind of encoding to be used
    Valid_encoding        : ['False', 'Position', 'Velocity',] # available encoding options
    PE_height             : 250 # number of frequency bands for positional encoding
    default_image_size    : [1280, 250] # default image size for positional encoding
    drop_height           : 156
    super_resolution_factor: 3

  cropped_tolerance  : 15 # number of pixels above and below the droplet to include in cropped images

Training:
  batch_size            : 16
  learning_rate         : 1e-4

  weight_decay          : 1e-5
  num_epochs            : 30
  
  Stride                : 10 #10
  window_Lenght         : 1

  Constant_feature_AE:
    Architecture: 'Autoencoder_CNNV1_0'
    Valid_architectures: ['Autoencoder_CNNV1_0', 'Autoencoder_CNNV2_0',]
    DropOut: True

  Constant_feature_LSTM:
    Hidden_size: 128
    Num_layers: 2
    DropOut: True

  num_workers           : 16
  GPU_temperature       : 67 # temperature threshold for GPU to wait/puase training
  checkpoint_save_freq  : 10
  hard_negative_mining  : False
  hard_mining_freq      : 2