reflection: 'off'

image_extension: '.png'
data_stride: 15
data_seq_len: 1
data_resize: [201, 201]

full_size_image_folder: 'frames_rotated'
cropped_image_folder: 'databases'
super_resolution_cropped : 'databases_SR'

SROF: 'result.csv' #'result_2Pass_corrected.csv'

Dataset:
  Dataset_Root          : '/media/d25u2/Dont/Viscosity' # base path to the dataset
  wide                  : False # using the full landscape images or only cropped droplets
  super_resolution      : False  # whether to use super-resolution cropped images
  resize: {
            True                  : [1280, 512], # for full landscape images
            False                 : [201 , 201]  # for cropped case
          }

  # deprecated please use Dataset_status in Training section for each model
  # reflection_removal    : False # whether to remove reflection artifacts in images

  embedding:
    positional_encoding   : 'False' # choosing what kind of encoding to be used
    Valid_encoding        : ['False', 'Position', 'Velocity',] # available encoding options
    PE_height             : 250 # number of frequency bands for positional encoding
    default_image_size    : [1280, 250] # default image size for positional encoding
    drop_height           : 156
    super_resolution_factor: 3

  cropped_tolerance  : 15 # number of pixels above and below the droplet to include in cropped images

Training:
  Show_plot            : False  # whether to show training plots
  USE_pretrained_AE    : False  # whether to use a pre-trained autoencoder model
  batch_size            : 16
  learning_rate         : 1e-4

  weight_decay          : 1e-5
  num_epochs            : 50
  

  Constant_feature_AE:
    Dataset_status: 'No_reflection' # 'No_reflection'  # 'Normal'
    Architecture: 'Autoencoder_CNNV1_0'
    Valid_architectures: ['Autoencoder_CNNV1_0', 'Autoencoder_CNNV3_0', 'Autoencoder_TransformerV2_0']
    DropOut: False #True
    AutoEncoder_layers: 9
    Stride                : 2 #10
    window_Lenght         : 1
    valid_latent_dim     : [128, 1024]

  Constant_feature_LSTM:
    Dataset_status: 'S4ORF_only' # 'No_reflection'  # 'Normal'
    learning_rate: 1e-4
    Hidden_size: 256
    Num_layers: 3 #2  
    DropOut: 0.2 #0.1
    Stride                : 1
    window_Lenght         : 10
    valid_embedding       : [128, 256]
    valid_window_Lenght   : [1, 10]

  Constant_features_Transformer:
    learning_rate: 1e-4
    d_model: 256
    nhead: 8
    num_layers: 8
    DropOut: 0.1
    Stride                : 1 
    window_Lenght         : 10
    valid_embedding       : [128, 256]
    valid_window_Lenght   : [1, 10, 100]

  num_workers           : 16
  GPU_temperature       : 67 # temperature threshold for GPU to wait/puase training
  checkpoint_save_freq  : 10
  hard_negative_mining  : False
  hard_mining_freq      : 2